### ISSUE TITLE
Stiff-ODEs with numerical Jacobian

### ISSUE THREAD

**Issue by dimaZloy** [SciML/DiffEqGPU.jl#188]
Hello,

Can you provide an example how to solve stiff-ode problems without providing an analytical Jacobian?

Thx, Dmitry

**Comment by ChrisRackauckas** [comment]
This repo currently requires an analytical Jacobian. However, given that it requires static behavior for compilation, you can just use `modelingtoolkitize` as shown in https://diffeq.sciml.ai/stable/tutorials/faster_ode_example/ to generate analytical Jacobians directly from the code.
