### ISSUE TITLE
Just wonder how faster DiffEqGPU.jl is compared to DifferentialEquations.jl

### ISSUE THREAD

**Issue by licheng0794** [SciML/DiffEqGPU.jl#204]
Any quantitative comparsion between two packages DiffEqGPU.jl and DifferentialEquations.jl? Thank you.

**Comment by ChrisRackauckas** [comment]
DiffEqGPU.jl is a part of DifferentialEquations.jl. It's the same interface and the same solvers. DiffEqGPU.jl is just some compilation tricks and helpers for using GPUs more effectively with DifferentialEquations.jl

You cannot put one number on it. Some cases without enough trajectories are slower: GPUs have a kernel cost overhead. Some cases with `EnsembleGPUKernel` are over 100x faster. It's application-dependent. We will be starting to write the paper on this library in the next month, aiming for it to be done in the next 6, and adding benchmarks to https://github.com/SciML/SciMLBenchmarks.jl, so definitely stay tuned and read those when they are ready. Until then, come up with your own benchmarks!
