### ISSUE TITLE
Compatibility with out of place definitions

### ISSUE THREAD

**Issue by rtburns-jpl** [SciML/DiffEqGPU.jl#26]
I'm having trouble generating a trivial example for Ensemble{CPU,GPU}Array. If I use the default EnsembleThreads() this runs fine, but uncommenting either of the DiffEqGPU-provided algs in my example causes failures. EnsembleGPUArray fails with `unsupported dynamic function invocation (call to myode)`, and EnsembleCPUArray fails with `LoadError: MethodError: no method matching myode(::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::SubArray{DiffEqBase.NullParameters,1,Array{DiffEqBase.NullParameters,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}, ::Float64)`. Am I doing something wrong here?

```julia
using OrdinaryDiffEq, DiffEqGPU

myode(u, p, t) = -u

u0 = 1.
prob = ODEProblem(myode, u0, (0., 5.) )

eprob = EnsembleProblem(prob)
sols = @time solve(eprob,
                   Tsit5(),
                   #EnsembleCPUArray(),
                   #EnsembleGPUArray(),
                   trajectories=10
                   )
```
This is using Julia v1.2.0, DiffEqGPU v0.4.0, OrdinaryDiffEq v5.20.1.

**Comment by ChrisRackauckas** [comment]
`myode(u, p, t) = -u`. This is using out of place. DiffEqGPU's methods are for in-place only right now.

**Comment by rtburns-jpl** [comment]
Ah, thanks! The following works for EnsembleCPU:
```
function myode(du, u, p, t)
    du[1] = -u[1]
end

u0 = [1.]
```
so this can be closed if out-of-place defs aren't an intended functionality.

For EnsembleGPU it looks like I'm getting the errors you noted on the CI in #15. Since you aren't seeing these locally may I ask what you're using for testing w.r.t. versions?

**Comment by ChrisRackauckas** [comment]
>so this can be closed if out-of-place defs aren't an intended functionality.

It can get added.

**Comment by ChrisRackauckas** [comment]
>For EnsembleGPU it looks like I'm getting the errors you noted on the CI in #15. Since you aren't seeing these locally may I ask what you're using for testing w.r.t. versions?

You need to be very careful and remove all allocations and bounds checks.

```julia
function myode(du, u, p, t)
    @inbounds du[1] = -u[1]
    nothing
end
```

**Comment by rtburns-jpl** [comment]
> You need to be very careful and remove all allocations and bounds checks.

Great, that did the trick. Thanks!
